### ISSUE TITLE
Modify the list to store the pointer of void (void*)

### ISSUE THREAD

**Issue by hhdang6637** [hhdang6637/pvtri_test#10]
Currently, the list only support to store the integer numbers. So, it not suitable to store other datas.

I want converte it to another data type that can store any data types. I suggest to use void* .

Do you have any ideas? 

If you don't understand why void* can store any data types, just let me know.

**Comment by nguyenhien1994** [comment]
Hi all, 
I resolved this in f9c86c635c7beace7980e41cf6276773cc848219
Please help to review this. @hhdang6637  @tranconghau @hvloi  @hvloi  
Thanks,
Hien Nguyen
