### ISSUE TITLE
Read and print CSV file:

### ISSUE THREAD

**Issue by nguyenhien1994** [hhdang6637/pvtri_test#13]
**Read and print CSV file:**
- Input: A CSV file with the following content:
```
Title1,Title2,Title3
one,two,three
example1,example2,example3
```
- Output: as below:
```
Title1      Title2      Title3
one         two         three
example1    example2    example3
```

**Comment by hhdang6637** [comment]
@quoctri1 , please update your status

**Comment by quoctri1** [comment]
I did it at csv_parser branch

**Comment by quoctri1** [comment]
![screenshot from 2018-06-01 18-05-54](https://user-images.githubusercontent.com/28265171/40838212-58adae16-65c7-11e8-880f-de09147bfee0.png)
This is my result.

**Comment by hhdang6637** [comment]
very good
